snd-soc-opencores_i2s-objs := opencores_i2s.o
obj-$(CONFIG_SND_SOC_OC_I2S) += snd-soc-opencores_i2s.o

snd-de1-soc-wm8731-midi-objs := de1-soc-wm8731-midi.o
obj-$(CONFIG_SND_SOC_DE1_WM8731_MIDI) += snd-de1-soc-wm8731-midi.o

snd-soc-hsynthdma-objs := hsynthdma.o
obj-$(CONFIG_SND_SOC_HSYNTHDMA) += snd-soc-hsynthdma.o
