snd-soc-opencores_i2s-objs := opencores_i2s.o
obj-$(CONFIG_SND_SOC_OC_I2S) += snd-soc-opencores_i2s.o

snd-de1-soc-wm8731-hsynth-objs := de1-soc-wm8731-hsynth.o
obj-$(CONFIG_SND_SOC_DE1_WM8731_HSYNTH) += snd-de1-soc-wm8731-hsynth.o

snd-soc-hsynthdma-objs := hsynthdma.o
obj-$(CONFIG_SND_SOC_HSYNTHDMA) += snd-soc-hsynthdma.o

snd-soc-hsynth-midi-objs := hsynth-midi.o
obj-$(CONFIG_SND_SOC_HSYNTH_MIDI) += snd-soc-hsynth-midi.o

snd-pcm5102-hsynth-objs := pcm5102-hsynth.o
obj-$(CONFIG_SND_SOC_PCM5102_HSYNTH) += snd-pcm5102-hsynth.o
